import type { Metadata } from "next";
import Sidebar from "./sidebar/page";

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <body>
        <div>
          <Sidebar />
        </div>
      </body>
    </div>
  );
}
