import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "./components/ui/sonner";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NewTube",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div lang="en">
      <Toaster/>
      <div className={inter.className}>
        {children}
      </div>
    </div>
  );
}
